#!/usr/bin/env python3
"""Emit objdiff.json: every .text translation unit, decompiled or not.

objdiff is the live matching feedback loop: pick a unit, write C, watch the
per-function match percentage. This tool generates its project config so the
WHOLE program is visible from day one:

  * All 247 .text units are listed, each pointing at its expected object
    (the retail slice assembled by ninja) as the diff target. Every function
    of the game appears in objdiff under its real mdebug name, whether or
    not anyone has started on it.
  * Units whose source file exists in src/ also get a base object (the plain
    compile of the C -- build/<v>/current/...). Units with no C yet have no
    base: objdiff shows their functions at 0%, which is the honest number.
  * Every linked data object from the committed data map is modelled too, as
    a target-only unit in a dedicated "data" category (see data_units): its
    total_data is the real linked byte count and matched_data is honestly 0
    until decompiled C data exists. objdiff measures those bytes from the
    `.split.*` sections directly, so no data symbols are required.
  * Builds go through `python tools/dispatch.py ninja <object>`: on Windows
    that forwards into the dev container, so clicking "build" in objdiff
    rebuilds exactly one ninja node wherever objdiff runs.

Unit names are derived from the mdebug source paths and never collide:

    ..\\nu2crash.ps2\\nucore\\nulist.c   -> nucore/nulist      [engine]
    .\\main.c                            -> game/main          [game]
    ../../src/newlib/libc/string/...    -> sdk/newlib/...     [sdk]
    graphdev.c (16 copies!)             -> sdk/sce/graphdev_127 etc.

The name doubles as the canonical source location: unit `nucore/nulist`
decompiles into src/nucore/nulist.c with a manifest at
config/<v>/status/nucore/nulist.toml.

objdiff.json is generated (never committed): it is a function of the
committed registries, the src/ tree, and the status manifests -- exactly
like build.ninja, and regenerated by the same commands (tools/gen_ninja.py
or configure.py). Pure Python; no toolchain needed.
"""
import argparse
import json
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from declib.tu import load_tu_runs, load_units, parse_toml_blocks
from gen_expected_s import unit_stem

MIN_VERSION = "2.7.0"

# decomp.me scratch defaults. The retail game/engine TUs (the ones with status
# manifests) are built by SN ProDG ee-gcc 2.95.2-EE, identified and locked as
# component `ee-gcc-tt`; its decomp.me equivalent is preset `ee-gcc2.95.2-273a`
# on the `ps2` platform (see docs/notes.md, 2026-07-07). c_flags mirror the
# `default` profile in config/<v>/profiles.toml so scratches build with the
# same flags matching uses.
SCRATCH_PLATFORM = "ps2"
SCRATCH_COMPILER = "ee-gcc2.95.2-273a"

CATEGORIES = [
    {"id": "game", "name": "Game code"},
    {"id": "engine", "name": "Nu engine"},
    {"id": "sdk", "name": "SDK / libc / CRT"},
    {"id": "data", "name": "Data"},
]


def _stem_of(path):
    return re.sub(r"\.[A-Za-z]+$", "", path.rsplit("/", 1)[-1])


def classify(mdebug_name):
    """(category, unit_name) from one mdebug source path.

    Three groups cover every unit (verified over all 267 paths):
    nu2crash.ps2 is the Nu engine; `.\\*.c` (plus vu/vu.c and one
    preprocessed temp file) is the game; everything else -- SCE libraries,
    the EE kernel glue, newlib, libgcc -- is SDK.
    """
    norm = mdebug_name.replace("\\", "/")
    stem = _stem_of(norm)
    if "nu2crash.ps2/" in norm:
        rel = norm.split("nu2crash.ps2/", 1)[1]
        return "engine", re.sub(r"\.[A-Za-z]+$", "", rel)
    if norm.startswith("./") or norm == "vu/vu.c" or norm.endswith(".i"):
        return "game", f"game/{stem}"
    if "/newlib/" in norm:
        rel = norm.split("/newlib/", 1)[1]
        return "sdk", "sdk/newlib/" + re.sub(r"\.[A-Za-z]+$", "", rel)
    if "/gcc/" in norm or stem in ("dp-bit", "fp-bit"):
        return "sdk", f"sdk/gcc/{stem}"
    return "sdk", f"sdk/sce/{stem}"


def unit_table(version):
    """[(index, stem, name, category)] for every .text TU, names unique.

    When several units share a derived name (16 graphdev.c, 4 libgcc2.c, two
    strlen implementations, ...) every member of the collision group gets its
    unit index appended, so none of them masquerades as "the" one.
    """
    raw = {int(r["index"]): r["name"] for r in parse_toml_blocks(
        ROOT / "config" / version / "units.toml",
        {"index": r"index = (\d+)", "name": r"name = '([^']*)'"})}
    stems = load_units()
    rows = []
    for unit, _addr in load_tu_runs():
        category, name = classify(raw[unit])
        name = re.sub(r"[^A-Za-z0-9_.\-/]", "_", name)
        rows.append((unit, unit_stem(unit, stems), name, category))

    counts = {}
    for _u, _s, name, _c in rows:
        counts[name] = counts.get(name, 0) + 1
    return [(u, s, f"{n}_{u:03d}" if counts[n] > 1 else n, c)
            for u, s, n, c in rows]


def data_units(version):
    """objdiff units for the linked data objects, in data-map order.

    Every object tools/gen_data_objects.py emits from the committed data map
    becomes a unit whose target is that expected data object and which has NO
    base -- there is no decompiled C data yet, so objdiff reports total_data
    honestly with zero matched. objdiff 3.7.2 measures data from the
    allocated `.split.*` section bytes, so these units carry a real
    total_data even though the objects hold no symbols. Names mirror the data
    map (`data/unit-NNNN`, `data/unassigned/<section>_<addr>`) and are prefixed
    `data/`, so they never collide with a `.text` unit; the shared
    object_groups() keeps the model and the built objects in lockstep.

    Pure over the committed data map -- no game files, no toolchain (it does
    not read the ELF; only the retail bytes inside the objects do, and those
    stay in gitignored expected/).
    """
    # Imported lazily: gen_data_objects pulls in the binutils path helpers,
    # which are irrelevant here (we never assemble), but keeping the import
    # local documents that this is the only coupling.
    from gen_data_objects import load_map, object_groups, NOBITS_SECTIONS
    ranges = [r for r in load_map(version)
              if r["section"] not in NOBITS_SECTIONS]
    units = []
    for stem, _entries in object_groups(ranges):
        units.append({
            "name": f"data/{stem}",
            "target_path": f"expected/{version}/data/{stem}.o",
            "metadata": {"progress_categories": ["data"]},
        })
    return units


def _default_cflags(version):
    """The `default` profile's flags, joined -- the ones matching compiles with."""
    profiles = ROOT / "config" / version / "profiles.toml"
    data = tomllib.loads(profiles.read_text())
    flags = data["profile"]["default"]["flags"]
    return " ".join(flags)


def _manifest_info(version):
    """{source_rel: (complete, has_matching)} from the status manifests.

    `has_matching` is True when at least one function is `matching` -- only
    then does the unit have a report-current object to score against (an
    all-`asm` unit is scored against its plain `current` object instead).
    """
    out = {}
    status_dir = ROOT / "config" / version / "status"
    if status_dir.is_dir():
        for m in sorted(status_dir.rglob("*.toml")):
            data = tomllib.loads(m.read_text())
            has_matching = any(f.get("state", "asm") == "matching"
                               for f in data.get("function", ()))
            out[data["source"]] = (bool(data.get("complete", False)),
                                   has_matching)
    return out


def emit_objdiff(version="pal103", out_path=None):
    """Write objdiff.json; returns the path written."""
    out_path = Path(out_path) if out_path else ROOT / "objdiff.json"
    manifests = _manifest_info(version)

    # Per-unit decomp.me scratch config: objdiff shows the "Create scratch"
    # button only for units carrying `scratch` with a platform + compiler
    # (schema puts it at units[].scratch, not project level). The retail
    # game/engine TUs are built by SN ProDG ee-gcc 2.95.2-EE, whose decomp.me
    # preset is `ee-gcc2.95.2-273a` on platform `ps2`; c_flags mirror the
    # `default` profile so scratches build with matching's flags.
    scratch = {
        "platform": SCRATCH_PLATFORM,
        "compiler": SCRATCH_COMPILER,
        "c_flags": _default_cflags(version),
    }

    units = []
    for _unit, stem, name, category in unit_table(version):
        source = f"src/{name}.c"
        entry = {
            "name": name,
            "target_path": f"expected/{version}/{stem}.o",
            "metadata": {
                "source_path": source,
                "progress_categories": [category],
            },
            "scratch": dict(scratch),
        }
        if (ROOT / source).is_file():
            if source in manifests:
                complete, has_matching = manifests[source]
                # The report base object: C functions with the hybrid's
                # .lit4/pseudo-op normalization, so a verified matching
                # function scores 100% (the raw current object misses by the
                # .lit4 pool placement). A unit with no `matching` function has
                # no report-current object, so it is scored against its plain
                # `current` object (a comment-only skeleton thus reads 0%).
                if has_matching:
                    entry["base_path"] = \
                        f"build/{version}/report-current/{name}.o"
                else:
                    entry["base_path"] = f"build/{version}/current/{name}.o"
                entry["metadata"]["complete"] = complete
            else:
                entry["base_path"] = f"build/{version}/current/{name}.o"
        units.append(entry)

    # Data units: one per linked data object, target only (honest 0 matched).
    units += data_units(version)

    config = {
        "min_version": MIN_VERSION,
        "custom_make": "python",
        "custom_args": ["tools/dispatch.py", "ninja"],
        "build_target": True,
        "watch_patterns": ["src/**/*.c", "include/**/*.h",
                           f"config/{version}/status/**/*.toml"],
        "progress_categories": CATEGORIES,
        "units": units,
    }
    out_path.write_text(json.dumps(config, indent=2) + "\n")
    return out_path


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--version", default="pal103")
    parser.add_argument("-o", "--output", help="output path (default: "
                        "objdiff.json at the repo root)")
    args = parser.parse_args()

    path = emit_objdiff(args.version, args.output)
    shown = path.resolve()
    try:
        shown = shown.relative_to(ROOT)
    except ValueError:
        pass
    all_units = json.loads(path.read_text())["units"]
    n_text = len(load_tu_runs())
    n_data = sum(1 for u in all_units if u["name"].startswith("data/"))
    with_base = sum(1 for u in all_units if "base_path" in u)
    print(f"wrote {Path(shown).as_posix()} (gitignored): {n_text} text units "
          f"({with_base} with a C base object) + {n_data} data units")
    return 0


if __name__ == "__main__":
    sys.exit(main())
