#!/usr/bin/env python3
"""Emit build.ninja: the incremental build graph over the proven pipeline.

The graph wires the existing tools together; it adds no logic of its own.
Per translation unit (247 .text TUs from the committed mdebug registries):

  expected   asm/text.s --gen_expected_s--> build/<v>/expected_s/NNN_<name>.s
                        --decompals-as----> expected/<v>/NNN_<name>.o
  current    src/<u>.c  --cc.py-----------> build/<v>/current/<u>.o
  matching   src/<u>.c + status manifest + fallback slices
                        --gen_hybrid.py---> build/<v>/matching/<u>.o
  equivalent same, with reviewed-equivalent functions compiled from C too

Phony targets: expected, current, matching, equivalent, fallback.
Default: expected + current + matching.

The file is generated (never committed) because the edge list is a function
of committed state: the unit registries, the src/ tree, and the status
manifests. Regenerate after adding a source file, a manifest, or a header:

    python tools/gen_ninja.py            (or python configure.py, which
                                          regenerates it after a split)

Commands in the graph invoke the Linux-only toolchain, so ninja itself runs
in the Containerfile image; from the Windows host use
`python tools/dispatch.py ninja <target>`.

Every path in the graph is repo-relative and POSIX, so the same build.ninja
works no matter where the repo is mounted. Pure Python; no toolchain needed
to generate.
"""
import argparse
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from declib.toolchain import AS, BINUTILS_DIR
from declib.tu import load_tu_runs, load_units
from gen_expected_s import unit_stem

_HEADER = """\
# Generated by tools/gen_ninja.py -- do not edit, do not commit.
# Regenerate with `python tools/gen_ninja.py` after adding sources,
# manifests, or headers.

ninja_required_version = 1.3
builddir = build
"""


def _esc(path):
    """Ninja-escape one path (which is always repo-relative POSIX here)."""
    return str(path).replace("$", "$$").replace(" ", "$ ").replace(":", "$:")


def _edge(rule, outs, ins=(), implicit=(), variables=()):
    line = (f"build {' '.join(_esc(o) for o in outs)}: {rule} "
            f"{' '.join(_esc(i) for i in ins)}")
    if implicit:
        line += " | " + " ".join(_esc(i) for i in implicit)
    lines = [line]
    for name, value in variables:
        lines.append(f"  {name} = {value}")
    return lines


def _sources(version):
    """[(src_rel, manifest_rel_or_None, profile)] for every C file in src/."""
    manifests = {}
    status_dir = ROOT / "config" / version / "status"
    if status_dir.is_dir():
        for m in sorted(status_dir.rglob("*.toml")):
            data = tomllib.loads(m.read_text())
            manifests[data["source"]] = (
                m.relative_to(ROOT).as_posix(),
                data.get("profile", "default"))
    out = []
    for src in sorted((ROOT / "src").rglob("*.c")):
        src_rel = src.relative_to(ROOT).as_posix()
        manifest, profile = manifests.get(src_rel, (None, "default"))
        out.append((src_rel, manifest, profile))
    return out


def emit_ninja(version="pal103", out_path=None):
    """Write build.ninja; returns the path written."""
    out_path = Path(out_path) if out_path else ROOT / "build.ninja"
    as_rel = (BINUTILS_DIR.relative_to(ROOT) / AS).as_posix()
    registries = [f"config/{version}/functions.toml",
                  f"config/{version}/units.toml"]
    headers = [f"include/{h.name}"
               for h in sorted((ROOT / "include").glob("*.h"))]
    profiles = f"config/{version}/profiles.toml"
    fallback_stamp = f"build/{version}/fallback/.stamp"

    L = [_HEADER]
    L += [
        "rule expected_s",
        f"  command = python tools/gen_expected_s.py --version {version}",
        "  description = split .text into per-TU expected assembly",
        "  restat = 1",
        "",
        "rule as_expected",
        f"  command = {as_rel} -EL -march=r5900 -I build/include"
        " -o $out $in",
        "  description = as $out",
        "",
        "rule fallback_slices",
        f"  command = python tools/gen_slices.py --version {version}"
        " && touch $out",
        "  description = cut per-function fallback slices",
        "",
        "rule cc",
        f"  command = python tools/cc.py $in -o $out --profile $profile"
        f" --version {version}",
        "  description = cc $out",
        "",
        "rule hybrid",
        "  command = python tools/gen_hybrid.py --manifest $manifest"
        f" --set $set -o $out --version {version}",
        "  description = hybrid ($set) $out",
        "",
        "rule link_image",
        f"  command = python tools/link_image.py --set $set"
        f" --version {version}",
        "  description = link $set image",
        "",
    ]

    # Expected objects: one splitter edge fans out into 247 assemble edges.
    unit_names = load_units()
    stems = [unit_stem(unit, unit_names) for unit, _addr in load_tu_runs()]
    expected_s = [f"build/{version}/expected_s/{s}.s" for s in stems]
    expected_o = [f"expected/{version}/{s}.o" for s in stems]
    L += _edge("expected_s", expected_s,
               implicit=["asm/text.s", *registries,
                         "tools/gen_expected_s.py"])
    L.append("")
    for s_path, o_path in zip(expected_s, expected_o):
        L += _edge("as_expected", [o_path], [s_path],
                   implicit=["build/include/macro.inc"])
    L.append("")

    # Fallback slices (inputs to every hybrid object).
    L += _edge("fallback_slices", [fallback_stamp],
               implicit=["asm/text.s", registries[0], "tools/gen_slices.py"])
    L.append("")

    # Current and hybrid objects per source file.
    current_o, matching_o, equivalent_o = [], [], []
    for src_rel, manifest, profile in _sources(version):
        rel = Path(src_rel).relative_to("src").with_suffix(".o").as_posix()
        cur = f"build/{version}/current/{rel}"
        current_o.append(cur)
        L += _edge("cc", [cur], [src_rel],
                   implicit=[profiles, "tools/cc.py", *headers],
                   variables=[("profile", profile)])
        if manifest is None:
            continue        # no manifest yet: no hybrid object (all-asm unit)
        for link_set, bucket in (("matching", matching_o),
                                 ("equivalent", equivalent_o)):
            out = f"build/{version}/{link_set}/{rel}"
            bucket.append(out)
            L += _edge("hybrid", [out], [src_rel, manifest],
                       implicit=[fallback_stamp, profiles,
                                 "tools/gen_hybrid.py", "tools/cc.py",
                                 *headers],
                       variables=[("manifest", manifest),
                                  ("set", link_set)])
    L.append("")

    # Full-image links: the matching image is the byte-identity gate
    # (`ninja verify-loaded`); the equivalent image only has to link.
    for link_set, objs in (("matching", matching_o),
                           ("equivalent", equivalent_o)):
        L += _edge("link_image", [f"build/{version}/image/{link_set}.bin"],
                   implicit=[*expected_o, *objs, "tools/link_image.py",
                             "tools/split_text.py"],
                   variables=[("set", link_set)])
    L.append("")

    for name, outs in (("expected", expected_o), ("current", current_o),
                       ("matching", matching_o), ("equivalent", equivalent_o),
                       ("fallback", [fallback_stamp]),
                       ("verify-loaded", [f"build/{version}/image/matching.bin"]),
                       ("image-equivalent",
                        [f"build/{version}/image/equivalent.bin"])):
        if outs:
            L += _edge("phony", [name], outs)
    L.append("default expected current matching")
    L.append("")

    out_path.write_text("\n".join(L))
    return out_path


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--version", default="pal103")
    parser.add_argument("-o", "--output", help="output path (default: "
                        "build.ninja at the repo root)")
    args = parser.parse_args()

    path = emit_ninja(args.version, args.output)
    rel = path.resolve()
    try:
        rel = rel.relative_to(ROOT)
    except ValueError:
        pass
    print(f"wrote {Path(rel).as_posix()} (gitignored)")
    if not args.output:
        # Regenerating the graph regenerates the objdiff config with it: the
        # two must agree on every object path.
        from gen_objdiff import emit_objdiff
        emit_objdiff(args.version)
        print("wrote objdiff.json (gitignored)")
    if not (ROOT / "asm" / "text.s").is_file():
        print("note: asm/text.s missing -- run `python configure.py` before "
              "building expected/fallback targets.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
