#!/usr/bin/env python3
"""Build the expected data objects from the committed data map.

For every PROGBITS range in config/<version>/data_map.toml (the .sbss/.bss
NOBITS ranges carry no file bytes and are skipped) this emits an `.incbin`
slice of the retail bytes and assembles it:

  expected/<version>/data/unit-NNNN.o           all ranges a unit owns, one
                                                object per unit (its future
                                                objdiff data target)
  expected/<version>/data/unassigned/<sec>_<addr>.o
                                                each gap / orphan range

Every range becomes its own input section, `.split.<sec>_<vram8hex>`, so the
image link script can place the pieces back at their exact addresses in
order -- the linked data sections are retail-byte-exact by construction
(tools/link_image.py consumes these; `ninja verify-loaded` proves it).

Needs the PS2 binutils: run in the Containerfile image (ninja target
`data`). Everything emitted is game-derived: objects land in gitignored
expected/, intermediates in build/.

Exit status is 0 only if every range assembled.
"""
import argparse
import subprocess
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from declib.toolchain import AS, h, tool_path
from declib.target import load_target

NOBITS_SECTIONS = {".sbss", ".bss"}


def load_map(version):
    """[{section,start,end,owner,evidence}] from the committed data map."""
    path = ROOT / "config" / version / "data_map.toml"
    if not path.is_file():
        raise SystemExit(f"{path.relative_to(ROOT)} missing; run "
                         "`python tools/extract_data_map.py` first.")
    return tomllib.loads(path.read_text())["range"]


def range_bytes(elf, sections_spec, pt_load, entry):
    """The retail file bytes of one map range."""
    if entry["section"] == "orphan":
        # Un-sectioned loaded bytes: locate via the PT_LOAD mapping.
        off = h(pt_load["offset"]) + (entry["start"] - h(pt_load["vaddr"]))
        return elf[off: off + entry["end"] - entry["start"]]
    sec = next(s for s in sections_spec["sections"]
               if s["name"] == entry["section"])
    off = h(sec["offset"]) + (entry["start"] - h(sec["addr"]))
    return elf[off: off + entry["end"] - entry["start"]]


def section_label(entry):
    sec = entry["section"].lstrip(".")
    return f"{sec}_{entry['start']:08x}"


def object_groups(ranges):
    """[(stem, [entries])] -- one object per owning unit, one per gap.

    Stems are relative to expected/<version>/data/ (no extension); the same
    grouping drives both object generation here and the image link
    (tools/link_image.py), so the two can never disagree on paths.
    """
    grouped = {}
    for entry in ranges:
        stem = (f"unassigned/{section_label(entry)}"
                if entry["owner"] == "unassigned" else entry["owner"])
        grouped.setdefault(stem, []).append(entry)
    return sorted(grouped.items())


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--version", default="pal103")
    args = parser.parse_args()

    as_bin = tool_path(AS)
    if not as_bin:
        print("PS2 binutils not found; run in the Containerfile image.",
              file=sys.stderr)
        return 2

    elf, sections_spec, pt_load = load_target(args.version)
    ranges = [r for r in load_map(args.version)
              if r["section"] not in NOBITS_SECTIONS]

    work = ROOT / "build" / args.version / "data_s"
    out_root = ROOT / "expected" / args.version / "data"
    (out_root / "unassigned").mkdir(parents=True, exist_ok=True)
    work.mkdir(parents=True, exist_ok=True)

    header = ("/* Generated by tools/gen_data_objects.py -- do not edit, do "
              "not commit (game-derived). */\n")
    built = 0
    groups = object_groups(ranges)
    for stem, entries in groups:
        s_path = work / f"{stem.replace('/', '_')}.s"
        pieces = [header]
        for entry in sorted(entries, key=lambda e: e["start"]):
            label = section_label(entry)
            bin_path = work / f"{label}.bin"
            bin_path.write_bytes(range_bytes(elf, sections_spec, pt_load,
                                             entry))
            pieces.append(f'\t.section .split.{label}, "a", @progbits\n'
                          f'\t.incbin "{bin_path.as_posix()}"\n')
        s_path.write_text("".join(pieces))
        obj = out_root / f"{stem}.o"
        try:
            subprocess.run([as_bin, "-EL", "-march=r5900",
                            "-o", str(obj), str(s_path)],
                           check=True, capture_output=True, text=True)
        except subprocess.CalledProcessError as exc:
            print(f"{stem}: as failed: "
                  f"{(exc.stderr or '').strip().splitlines()[:2]}",
                  file=sys.stderr)
            return 1
        built += 1

    n_gap = sum(1 for stem, _e in groups if stem.startswith("unassigned/"))
    print(f"{built} data objects -> "
          f"{out_root.relative_to(ROOT).as_posix()}/ "
          f"({built - n_gap} per-unit, {n_gap} unassigned; "
          f"{len(ranges)} ranges, gitignored)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
