#!/usr/bin/env python3
"""Whitelist-filter the objdiff report into the only report that gets published.

build/<v>/report.json (`ninja report`) is generated by the pinned objdiff-cli
from objects that embed retail bytes, so it is never uploaded as-is. This tool
copies ONLY whitelisted fields into build/<v>/report.public.json -- the file
the protected workflow ships (decomp.dev artifact, gh-pages). The filter is a
whitelist, not a blacklist: a field objdiff adds in a future version is
dropped until someone reviews it and adds it here.

After filtering, every string in the OUTPUT is scanned; publication aborts
(exit 1) if any string

  * references orig/ (game files must never even be named outside the repo),
  * is an absolute path (leaks runner layout),
  * looks like a hex or base64 blob (embedded bytes hiding in a text field).

Function names, addresses and sizes pass on purpose: they are facts already
committed in the public config/ registries (functions.toml et al).

One honesty rule beyond the whitelist: objdiff-cli emits derived measures
even when their total is zero -- matched_data*/complete_data* for a code unit
with no data, matched_code*/fuzzy for a data unit with no code -- each reading
as "100% of nothing". Where a measures block's total is absent or 0, the
measures that total governs are dropped and the honest total is kept; a block
with a real total keeps them. This never invents a value.

Stdlib only; no toolchain and no game files needed.
"""
import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Every measure objdiff-cli 3.7.2 can emit (aggregate counts/percentages).
MEASURE_KEYS = frozenset({
    "fuzzy_match_percent",
    "total_code", "matched_code", "matched_code_percent",
    "complete_code", "complete_code_percent",
    "total_data", "matched_data", "matched_data_percent",
    "complete_data", "complete_data_percent",
    "total_functions", "matched_functions", "matched_functions_percent",
    "total_units", "complete_units",
})
UNIT_METADATA_KEYS = frozenset({"complete", "source_path",
                                "progress_categories"})

# A derived measure means nothing when its total is absent or zero. objdiff-cli
# still emits e.g. matched_code_percent=100 for a data-only unit (zero code) and
# matched_data_percent=100 for every code unit (zero data) -- "100% of nothing".
# For each total we drop exactly the derived measures it governs, keeping the
# honest total (an explicit 0 or its absence). A block with a real total keeps
# them, so genuine progress -- code today, C-modelled data tomorrow -- passes
# through untouched. fuzzy_match_percent is code-weighted in this project, so it
# rides with total_code (a data-only unit's fuzzy is objdiff's 100%-of-no-code
# artifact; revisit if C data ever contributes to a unit's fuzzy score). This
# never invents a value. See docs/notes.md (honest data/code metrics).
HOLLOW_WHEN_TOTAL_ZERO = {
    "total_code": ("matched_code", "matched_code_percent",
                   "complete_code", "complete_code_percent",
                   "fuzzy_match_percent"),
    "total_data": ("matched_data", "matched_data_percent",
                   "complete_data", "complete_data_percent"),
    "total_functions": ("matched_functions", "matched_functions_percent"),
}

ORIG_RE = re.compile(r"(^|[\\/])orig([\\/]|$)", re.IGNORECASE)
ABS_PATH_RE = re.compile(r"^([A-Za-z]:[\\/]|[\\/])")
HEX_BLOB_RE = re.compile(r"^[0-9a-fA-F]{32,}$")
B64_BLOB_RE = re.compile(r"^[A-Za-z0-9+/]{64,}={0,2}$")


def _measure_zero_or_absent(measures, key):
    """True if a numeric measure is missing or equals zero.

    objdiff-cli renders integer measures as JSON strings ("0"), so accept
    both the string and numeric forms; a value that cannot be read as a
    number is treated as present (do not strip on garbage).
    """
    if key not in measures:
        return True
    try:
        return float(measures[key]) == 0.0
    except (TypeError, ValueError):
        return False


def _strip_hollow_measures(measures):
    """Drop derived measures in place whose total is absent or zero.

    Keeps the honest totals; removes only the matched_/complete_/percent
    measures that would otherwise report progress against nothing. Applied to
    every measures block (report, unit, category) independently, so a block
    that genuinely has code or data keeps its measures.
    """
    for total, derived in HOLLOW_WHEN_TOTAL_ZERO.items():
        if _measure_zero_or_absent(measures, total):
            for key in derived:
                measures.pop(key, None)


def _keep(src, dst, keys, dropped, where):
    for key, value in src.items():
        if key in keys:
            dst[key] = value
        else:
            dropped.add(f"{where}.{key}")


def _clean_symbol(sym, dropped, where):
    out = {}
    _keep(sym, out, ("name", "size", "address", "fuzzy_match_percent"),
          dropped, where)
    return out


def _clean_section(sec, dropped, where):
    out = {}
    _keep(sec, out, ("name", "size", "fuzzy_match_percent"), dropped, where)
    return out


def sanitize(report):
    """(public_report, dropped_field_names) -- pure whitelist projection.

    The output must stay a strict SUBSET of objdiff's Report schema (no
    added fields): decomp.dev parses the artifact as a protobuf-JSON
    Report, and unknown fields would break it.
    """
    dropped = set()
    public = {}
    if "version" in report:
        public["version"] = report["version"]

    public["measures"] = {}
    _keep(report.get("measures", {}), public["measures"], MEASURE_KEYS,
          dropped, "measures")
    _strip_hollow_measures(public["measures"])

    public["units"] = []
    for unit in report.get("units", []):
        u = {"name": unit["name"], "measures": {}}
        _keep(unit.get("measures", {}), u["measures"], MEASURE_KEYS,
              dropped, "unit.measures")
        _strip_hollow_measures(u["measures"])
        u["sections"] = [_clean_section(s, dropped, "unit.section")
                         for s in unit.get("sections", [])]
        u["functions"] = [_clean_symbol(f, dropped, "unit.function")
                          for f in unit.get("functions", [])]
        u["metadata"] = {}
        _keep(unit.get("metadata", {}), u["metadata"], UNIT_METADATA_KEYS,
              dropped, "unit.metadata")
        for key in unit:
            if key not in ("name", "measures", "sections", "functions",
                           "metadata"):
                dropped.add(f"unit.{key}")
        public["units"].append(u)

    public["categories"] = []
    for cat in report.get("categories", []):
        c = {"id": cat["id"], "name": cat["name"], "measures": {}}
        _keep(cat.get("measures", {}), c["measures"], MEASURE_KEYS,
              dropped, "category.measures")
        _strip_hollow_measures(c["measures"])
        for key in cat:
            if key not in ("id", "name", "measures"):
                dropped.add(f"category.{key}")
        public["categories"].append(c)

    for key in report:
        if key not in ("version", "measures", "units", "categories"):
            dropped.add(key)
    return public, dropped


def violations(obj, where="report"):
    """Every publication-blocking string in an already-sanitized tree."""
    found = []
    if isinstance(obj, dict):
        for key, value in obj.items():
            found += violations(value, f"{where}.{key}")
    elif isinstance(obj, list):
        for i, value in enumerate(obj):
            found += violations(value, f"{where}[{i}]")
    elif isinstance(obj, str):
        if ORIG_RE.search(obj):
            found.append(f"{where}: references orig/ ({obj!r})")
        elif ABS_PATH_RE.match(obj):
            found.append(f"{where}: absolute path ({obj!r})")
        elif HEX_BLOB_RE.match(obj):
            found.append(f"{where}: hex blob ({obj[:32]!r}...)")
        elif B64_BLOB_RE.match(obj):
            found.append(f"{where}: base64 blob ({obj[:32]!r}...)")
    return found


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("input", nargs="?",
                        help="report to sanitize (default: "
                             "build/<version>/report.json)")
    parser.add_argument("-o", "--output",
                        help="default: build/<version>/report.public.json")
    parser.add_argument("--version", default="pal103")
    args = parser.parse_args()

    in_path = Path(args.input) if args.input \
        else ROOT / "build" / args.version / "report.json"
    out_path = Path(args.output) if args.output \
        else ROOT / "build" / args.version / "report.public.json"
    if not in_path.is_file():
        print(f"{in_path} missing; run `ninja report` first.", file=sys.stderr)
        return 2

    report = json.loads(in_path.read_text())
    public, dropped = sanitize(report)

    problems = violations(public)
    if problems:
        print("REFUSING to write a publishable report:", file=sys.stderr)
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        return 1

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(public, separators=(",", ":")) + "\n")
    n_funcs = sum(len(u["functions"]) for u in public["units"])
    print(f"wrote {out_path} ({len(public['units'])} units, {n_funcs} "
          f"functions, {out_path.stat().st_size} bytes)")
    if dropped:
        print(f"dropped non-whitelisted fields: {', '.join(sorted(dropped))}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
