"""config/pal103/symbol_addrs.txt -> ld PROVIDE script, so mod code links
against every retail symbol at its fixed address. PROVIDE (not `=`) lets a
mod define its own copy of a name without a duplicate-definition error."""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent

LINE_RE = re.compile(
    r"^(?P<name>[A-Za-z_][A-Za-z0-9_$]*)\s*=\s*(?P<addr>0x[0-9a-fA-F]+)\s*;"
    r"(?:\s*//\s*(?P<attrs>.*))?$")


def symbol_table(version="pal103"):
    """{name: (address, is_function)}; first occurrence wins."""
    path = ROOT / "config" / version / "symbol_addrs.txt"
    table = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("//"):
            continue
        m = LINE_RE.match(line)
        if not m:
            raise ValueError(f"{path}: unparseable line: {line}")
        name = m.group("name")
        if name in table:
            continue
        attrs = m.group("attrs") or ""
        table[name] = (int(m.group("addr"), 16), "type:func" in attrs)
    return table


def provide_script(version="pal103"):
    table = symbol_table(version)
    lines = [f"PROVIDE({name} = 0x{addr:08X});"
             for name, (addr, _isfunc) in
             sorted(table.items(), key=lambda kv: kv[1][0])]
    return ("/* generated by tools/modsdk/gen_symbols.py from "
            f"config/{version}/symbol_addrs.txt -- do not edit */\n"
            + "\n".join(lines) + "\n")


def main():
    out = ROOT / "build" / "pal103" / "mods" / "retail_symbols.ld"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(provide_script())
    print(f"wrote {len(symbol_table())} symbols -> {out}")


if __name__ == "__main__":
    main()
